spring:
  application:
    name: servidor-zuul
server:
  port: 7000
zuul:
  routes:
    serv-vuelos:
      path: /svuelos/**
      service-id: servicio-vuelos
    serv-hoteles:
      path: /shoteles/**
      service-id: servicio-hoteles
    serv-reservas:
      path: /sreservas/**
      service-id: servicio-reservas
eureka:
  client:
    service-url:
      default-zone: http://localhost:876/eureka
